bundler_args: --binstubs
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.1
  - 2.2.10
  - 2.3.5
  - 2.4.7
  - 2.5.6
  - 2.6.4

notifications:
  irc: "irc.freenode.org#axlsx"
  email:
    recipients:
      - noel@peden.biz
    on_success: always

